### ISSUE TITLE
I did not find my app in the List

### ISSUE THREAD

**Issue by marwa-eltayeb** [pinkeshdarji/FlutterCreateSubmissions2019#9]
I submitted my app. It is called guess_the_number, and I did not find it among the other apps.

This is the link of my app that I developed:
https://github.com/Marwa-Eltayeb/Guess_the_number

Please, any one tell me why?!!
What is the problem?!!

**Comment by pinkeshdarji** [comment]
@Marwa-Eltayeb You can contribute here.
